name: Lint, Test, and Deploy
on: [push, workflow_dispatch]
jobs:
  Build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Get Repo
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Build Project
        run: npm run build
  Lint: 
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Lint Repo
        run: npm run lint